name: Build BoredOS ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone BoredOS repository
        run: |
          git clone --recurse-submodules https://github.com/BoredOS/BoredOS.git
          cd BoredOS

      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/bin
            ~/.cache/limine
          key: ${{ runner.os }}-boredos-toolchain

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm xorriso \
            mtools dosfstools grub-pc-bin \
            build-essential bison flex libgmp-dev \
            libmpc-dev libmpfr-dev texinfo \
            wget curl
          cd BoredOS
          chmod +x tools/install_deps_linux.sh
          ./tools/install_deps_linux.sh

      - name: Build BoredOS ISO
        run: |
          cd BoredOS
          make -j$(nproc) boredos.iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: boredos-iso
          path: BoredOS/boredos.iso
          retention-days: 30